export const works = [
  {
    name: 'ZR.RU',
    image: '/zrru.svg',
    technology: [
      'Next.js',
      'SSG',
      'SSR',
      'Tanstack',
      'React.js',
      'Typescript',
      'Styled-components',
      'Storybook',
    ],
    siteLink: 'https://www.zr.ru',
  },
  {
    name: 'AMP version for ZR.RU',
    image: '/ampzrru.svg',
    technology: ['React.js', 'SSR', 'Typescript', 'Styled-components'],
    code: 'https://github.com/aermilina/example-react-amp',
  },
  {
    name: 'Statistics interface for KP-IT',
    image: '/kpproject.svg',
    technology: ['Next.js', 'Typescript', 'Axios', 'Formik', 'Yup', 'Material UI'],
    code: 'https://github.com/aermilina/statsboard_example',
  },
  {
    name: 'Tank widget for Wargaming',
    image: '/wot.svg',
    technology: ['VanillaJS', 'Typescript', 'Popper.js', 'noUiSlider', 'HTML', 'SCSS', 'Vite '],
    code: 'https://github.com/aermilina/wot',
    siteLink: 'https://aermilina.github.io/wot/',
  },
  {
    name: 'Test dashboard for Kameleoon',
    image: '/kameleoon.svg',
    technology: ['React', 'React Hooks', 'Typescript', 'Scss', 'Vite', 'Vitetest'],
    code: 'https://github.com/aermilina/test_dashboard',
  },
  {
    name: 'Frontend Jobs TG Bot',
    image: '/frontjobs.svg',
    technology: ['Python', 'Telegram Bot API', 'AI'],
    code: 'https://github.com/aermilina/frontjobs',
    siteLink: 'https://t.me/FrontendinRemote',
  },
  {
    name: 'Test Case for CADExachange',
    image: '/cadex.svg',
    technology: [
      'Next.js',
      'React',
      'Typescript',
      'Next API Router',
      'Formik',
      'Yup',
      'Material UI',
      'Styled-components',
    ],
    code: 'https://github.com/aermilina/testcase-cadex',
    siteLink: 'https://testcase-cadex-2.vercel.app/',
  },
  {
    name: 'Test Case for INMYROOMS',
    image: '/inmyrooms.svg',
    technology: ['React', 'Typescript', 'Scss'],
    code: 'https://github.com/aermilina/tapbar_inmyrooms',
    siteLink: 'https://aermilina.github.io/tapbar_inmyrooms/',
  },
  {
    name: 'Test Case for Realmond',
    image: '/testrealmond.svg',
    technology: ['Next.js', 'React', 'Typescript', 'Tailwind Css'],
    code: 'https://github.com/aermilina/userlist_realmond',
  },
  {
    name: 'Portfolio site',
    description: 'This is my portfolio site',
    image: '/portfolio.svg',
    technology: ['Next.js', 'React', 'Typescript', 'Tailwind.css'],
    code: 'https://github.com/aermilina/aermilina.github.io',
  },
];
